=== klestardb/klestardb/src/assets/schema_character.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "$defs": {
    "elementType": {
      "enum": [ "炎", "水", "雷", "光", "闇" ]
    },
    "raceType": {
      "enum": [ "人間", "魔族", "神族" ]
    },
    "roleType": {
      "enum": [ "ATK", "SPD", "DEF", "SUP", "HEAL" ]
    },
    "weaponType": {
      "enum": [ "斬撃", "打撃", "魔法" ]
    },

    "buffType": {
      "enum": [ "ATK", "重さ", "ノーツ前進", "ノーツ移動", "CT短縮", "EX上昇", "バリア(HP)", "バリア(回数)", "チャージ付与", "ステルス付与", "サブ属性付与" ]
    },
    "debuffType": {
      "enum": [ "ATK", "重さ", "ノックバック", "ノーツ強制移動", "CT延長", "被ダメ増", "毒", "麻痺", "混乱", "萎縮", "封印", "火傷", "凍傷" ]
    },
    "targetType": {
      "enum": [ "自身", "単体", "範囲", "種族", "属性", "全体" ]
    }
  },

  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "date",
      "name",
      "element",
      "race",
      "role",
      "weapon",
      "hp",
      "ex",
      "atk",
      "crit",
      "exup",
      "ctmin",
      "ctmax",
      "skills"
    ],
    "additionalProperties": false,
    "properties": {
      "id": { "type": "string" },
      "name": { "type": "string" },
      "date": { "type": "string" },
      "cv": { "type": "string" },
      "star": { "type": "integer" },
      "element": { "$ref": "#/$defs/elementType" },
      "race": { "$ref": "#/$defs/raceType" },
      "role": { "$ref": "#/$defs/roleType" },
      "weapon": { "$ref": "#/$defs/weaponType" },
      "hp": { "type": "number" },
      "ex": { "type": "number" },
      "atk": { "type": "number" },
      "crit": { "type": "number" },
      "exup": { "type": "number" },
      "ctmin": { "type": "number" },
      "ctmax": { "type": "number" },
      "skills": {
        "type": "array"
      },
      "note": { "type": "string" }
    }
  }
}

=== klestardb/klestardb/src/assets/character2023.json
[
    {
        "id": "006001",
        "date": "2023/07/07",
        "name": "未完の魔王 クロト",
        "cv": "儚井あわ",
        "star": 1,
        "element": "闇",
        "race": "人間",
        "role": "ATK",
        "weapon": "打撃",
        "hp": 539,
        "ex": 20,
        "atk": 109,
        "crit": 5.0,
        "exup": 54,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": "009001",
        "date": "2023/07/07",
        "name": "おちゃめな副会長 セーラ",
        "cv": "夏野ぱいん",
        "star": 1,
        "element": "雷",
        "race": "人間",
        "role": "SUP",
        "weapon": "魔法",
        "hp": 437,
        "ex": 20,
        "atk": 70,
        "crit": 3.0,
        "exup": 66,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": "011001",
        "date": "2023/07/07",
        "name": "コモンシールダー マトイ",
        "cv": "花猫のの",
        "star": 1,
        "element": "雷",
        "race": "人間",
        "role": "DEF",
        "weapon": "斬撃",
        "hp": 565,
        "ex": 20,
        "atk": 136,
        "crit": 8.0,
        "exup": 70,
        "ctmin": 21,
        "ctmax": 25,
        "skills": [
        ]
    },
    {
        "id": "017001",
        "date": "2023/07/07",
        "name": "烈火の料理人 蛍火",
        "cv": "猫屋敷舞",
        "star": 1,
        "element": "炎",
        "race": "魔族",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 499,
        "ex": 20,
        "atk": 102,
        "crit": 5.0,
        "exup": 46,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": "019001",
        "date": "2023/07/07",
        "name": "紫電のくノ一 せつな",
        "cv": "八ッ橋しなもん",
        "star": 1,
        "element": "雷",
        "race": "魔族",
        "role": "SPD",
        "weapon": "魔法",
        "hp": 198,
        "ex": 20,
        "atk": 57,
        "crit": 3.0,
        "exup": 10,
        "ctmin": 10,
        "ctmax": 14,
        "skills": [
        ]
    },
    {
        "id": "020001",
        "date": "2023/07/07",
        "name": "蒼穹の仮想歌姫 ルルカ",
        "cv": "秋元にゃん",
        "star": 1,
        "element": "水",
        "race": "魔族",
        "role": "SUP",
        "weapon": "魔法",
        "hp": 414,
        "ex": 20,
        "atk": 64,
        "crit": 3.0,
        "exup": 66,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": "021001",
        "date": "2023/07/07",
        "name": "お気楽バイト天使 環",
        "cv": "西園かなえ",
        "star": 1,
        "element": "雷",
        "race": "神族",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 388,
        "ex": 20,
        "atk": 98,
        "crit": 5.0,
        "exup": 44,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": "025001",
        "date": "2023/07/07",
        "name": "銀盤に舞う女王 舞亜",
        "cv": "赤丸いくら",
        "star": 1,
        "element": "水",
        "race": "人間",
        "role": "SPD",
        "weapon": "斬撃",
        "hp": 282,
        "ex": 20,
        "atk": 61,
        "crit": 3.0,
        "exup": 16,
        "ctmin": 11,
        "ctmax": 15,
        "skills": [
        ]
    },
    {
        "id": "035001",
        "date": "2023/07/07",
        "name": "炎銃のバンデッド セナリィ",
        "cv": "宇井好",
        "star": 1,
        "element": "炎",
        "race": "人間",
        "role": "ATK",
        "weapon": "打撃",
        "hp": 422,
        "ex": 20,
        "atk": 113,
        "crit": 5.0,
        "exup": 48,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": "050001",
        "date": "2023/07/07",
        "name": "ヒール＋ペイン フロレンシア",
        "cv": "如月たま",
        "star": 1,
        "element": "闇",
        "race": "神族",
        "role": "HEAL",
        "weapon": "打撃",
        "hp": 722,
        "ex": 20,
        "atk": 36,
        "crit": 3.0,
        "exup": 72,
        "ctmin": 18,
        "ctmax": 22,
        "skills": [
        ]
    },
    {
        "id": "062001",
        "date": "2023/07/07",
        "name": "星選の名探偵 ジュエリー",
        "cv": "乃葉奈",
        "star": 1,
        "element": "光",
        "race": "人間",
        "role": "SUP",
        "weapon": "打撃",
        "hp": 454,
        "ex": 20,
        "atk": 51,
        "crit": 3.0,
        "exup": 68,
        "ctmin": 14,
        "ctmax": 18,
        "skills": [
        ]
    },
    {
        "id": "064001",
        "date": "2023/07/07",
        "name": "ブラッディマリー マリーベル",
        "cv": "紅寧",
        "star": 1,
        "element": "闇",
        "race": "人間",
        "role": "ATK",
        "weapon": "打撃",
        "hp": 427,
        "ex": 20,
        "atk": 113,
        "crit": 5.0,
        "exup": 54,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },

    {
        "id": "005001",
        "date": "2023/07/07",
        "name": "氷刃の妖精 ソフィア",
        "cv": "姫宮にいな",
        "star": 2,
        "element": "水",
        "race": "魔族",
        "role": "DEF",
        "weapon": "斬撃",
        "hp": 873,
        "ex": 25,
        "atk": 176,
        "crit": 8.0,
        "exup": 95,
        "ctmin": 19,
        "ctmax": 23,
        "skills": [
        ]
    },
    {
        "id": "007001",
        "date": "2023/07/07",
        "name": "加護の角笛 ルリエル",
        "cv": "春咲さくら",
        "star": 2,
        "element": "光",
        "race": "神族",
        "role": "SUP",
        "weapon": "魔法",
        "hp": 510,
        "ex": 25,
        "atk": 68,
        "crit": 3.0,
        "exup": 80,
        "ctmin": 12,
        "ctmax": 16,
        "skills": [
        ]
    },
    {
        "id": "013001",
        "date": "2023/07/07",
        "name": "弱きを守る斧槍 ユウリ",
        "cv": "椎名みこ",
        "star": 2,
        "element": "炎",
        "race": "魔族",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 712,
        "ex": 25,
        "atk": 176,
        "crit": 5.0,
        "exup": 57,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": "014001",
        "date": "2023/07/07",
        "name": "暁の導き手 トワ先生",
        "cv": "木ノ下やや",
        "star": 2,
        "element": "水",
        "race": "人間",
        "role": "HEAL",
        "weapon": "魔法",
        "hp": 1134,
        "ex": 25,
        "atk": 48,
        "crit": 3.0,
        "exup": 95,
        "ctmin": 18,
        "ctmax": 22,
        "skills": [
        ]
    },
    {
        "id": "016001",
        "date": "2023/07/07",
        "name": "ゴーストネイバー ヒトリ",
        "cv": "花杜めい",
        "star": 2,
        "element": "闇",
        "race": "人間",
        "role": "SUP",
        "weapon": "魔法",
        "hp": 571,
        "ex": 25,
        "atk": 91,
        "crit": 3.0,
        "exup": 85,
        "ctmin": 14,
        "ctmax": 18,
        "skills": [
        ]
    },
    {
        "id": "018001",
        "date": "2023/07/07",
        "name": "轟雷の華騎士 エリス",
        "cv": "百合本花",
        "star": 2,
        "element": "雷",
        "race": "神族",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 669,
        "ex": 25,
        "atk": 160,
        "crit": 5.0,
        "exup": 62,
        "ctmin": 16,
        "ctmax": 20,
        "skills": [
        ]
    },
    {
        "id": "023001",
        "date": "2023/07/07",
        "name": "淑やかシスター？ シャロン",
        "cv": "姫宮にいな",
        "star": 2,
        "element": "水",
        "race": "神族",
        "role": "SUP",
        "weapon": "打撃",
        "hp": 699,
        "ex": 25,
        "atk": 84,
        "crit": 3.0,
        "exup": 90,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": "029001",
        "date": "2023/07/07",
        "name": "嗜虐の貴族令嬢 シャルレーヌ",
        "cv": "九蓮ほう子",
        "star": 2,
        "element": "光",
        "race": "魔族",
        "role": "SUP",
        "weapon": "魔法",
        "hp": 629,
        "ex": 25,
        "atk": 92,
        "crit": 3.0,
        "exup": 82,
        "ctmin": 14,
        "ctmax": 18,
        "skills": [
        ]
    },
    {
        "id": "033001",
        "date": "2023/07/07",
        "name": "仮面の暗黒騎士 アニュラス",
        "cv": "一ノ瀬こまち",
        "star": 2,
        "element": "闇",
        "race": "人間",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 548,
        "ex": 25,
        "atk": 162,
        "crit": 5.0,
        "exup": 60,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": "034001",
        "date": "2023/07/07",
        "name": "お仕えしますワン カティア",
        "cv": "生島公",
        "star": 2,
        "element": "炎",
        "race": "魔族",
        "role": "SPD",
        "weapon": "打撃",
        "hp": 394,
        "ex": 25,
        "atk": 117,
        "crit": 3.0,
        "exup": 30,
        "ctmin": 11,
        "ctmax": 15,
        "skills": [
        ]
    },
    {
        "id": "037001",
        "date": "2023/07/07",
        "name": "ふわふわスイート サラン",
        "cv": "春乃いろは",
        "star": 2,
        "element": "光",
        "race": "人間",
        "role": "DEF",
        "weapon": "斬撃",
        "hp": 949,
        "ex": 25,
        "atk": 214,
        "crit": 8.0,
        "exup": 102,
        "ctmin": 22,
        "ctmax": 26,
        "skills": [
        ]
    },
    {
        "id": "049001",
        "date": "2023/07/07",
        "name": "善哉童子 紅明",
        "cv": "まるちびたみん",
        "star": 2,
        "element": "雷",
        "race": "魔族",
        "role": "HEAL",
        "weapon": "打撃",
        "hp": 1089,
        "ex": 25,
        "atk": 61,
        "crit": 3.0,
        "exup": 90,
        "ctmin": 19,
        "ctmax": 23,
        "skills": [
        ]
    },


    {
        "id": "001001",
        "date": "2023/07/07",
        "name": "流星の姫君 フィオナ",
        "cv": "月城黒魅",
        "star": 3,
        "element": "闇",
        "race": "人間",
        "role": "ATK",
        "weapon": "魔法",
        "hp": 1059,
        "ex": 30,
        "atk": 250,
        "crit": 5.0,
        "exup": 81,
