=== klestardb/klestardb/src/assets/schema_starknights.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",

  "$defs": {
    "elementType": {
      "enum": [ "炎", "水", "雷", "光", "闇" ]
    },
    "raceType": {
      "enum": [ "人間", "魔族", "神族" ]
    },
    "roleType": {
      "enum": [ "ATK", "SPD", "DEF", "SUP", "HEAL" ]
    },
    "weaponType": {
      "enum": [ "斬撃", "打撃", "魔法" ]
    },
    "factionType": {
      "enum": [ "新星学園", "流星学園", "流星学園附属", "守護天使", "ネビュラ", "コラプサー", "その他", "" ]
    },
    "gradeType": {
      "enum": [ "1年生", "2年生", "3年生", "教師・その他" ]
    },

    "buffType": {
      "enum": [
        "ATK", "クリティカル確率", "クリティカルダメージ", "ノックバック軽減", "ノックバック無効", "カウンター",
        "ノーツ前進", "ノーツ移動", "行動CT", "EX上昇", "消費EX減少", "バリア(HP)", "バリア(回数)", "チャージ", "ステルス", "サブ属性"
      ]
    },
    "debuffType": {
      "enum": [
        "ATK", "重さ", "ノックバック増加", "ノーツ強制移動", "CT延長", "ダメージ増加", "毒", "麻痺", "混乱", "萎縮", "封印", "火傷", "凍傷"
      ]
    },
    "targetType": {
      "enum": [ "自身", "単体", "範囲", "種族", "属性", "全体" ]
    }
  },

  "type": "array",
  "items": {
    "type": "object",
    "required": [
      "id",
      "date",
      "name",
      "element",
      "race",
      "role",
      "weapon",
      "hp",
      "ex",
      "atk",
      "crit",
      "exup",
      "ctmin",
      "ctmax",
      "skills"
    ],
    "additionalProperties": false,
    "properties": {
      "id": { "type": "integer" },
      "date": { "type": "string" },
      "name": { "type": "string" },
      "cv": { "type": "string" },
      "star": { "type": "integer" },
      "faction": { "$ref": "#/$defs/factionType" },
      "grade": { "$ref": "#/$defs/gradeType" },
      "element": { "$ref": "#/$defs/elementType" },
      "race": { "$ref": "#/$defs/raceType" },
      "role": { "$ref": "#/$defs/roleType" },
      "weapon": { "$ref": "#/$defs/weaponType" },
      "hp": { "type": "number" },
      "ex": { "type": "number" },
      "atk": { "type": "number" },
      "crit": { "type": "number" },
      "exup": { "type": "number" },
      "ctmin": { "type": "number" },
      "ctmax": { "type": "number" },
      "skills": { "type": "array" },
      "tags": { "type": "array" },
      "note": { "type": "string" }
    }
  }
}

=== klestardb/klestardb/src/assets/starknights2024.json
[
    {
        "id": 1003002,
        "date": "2024/01/01",
        "name": "招福の明星 ヴィーナス",
        "cv": "天井めろん",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 3,
        "element": "雷",
        "race": "人間",
        "role": "ATK",
        "weapon": "魔法",
        "hp": 1164,
        "ex": 30,
        "atk": 263,
        "crit": 5.0,
        "exup": 60,
        "ctmin": 16,
        "ctmax": 20,
        "skills": [
        ]
    },
    {
        "id": 1058001,
        "date": "2024/01/01",
        "name": "舞うは九浄の桜花 ヘレナ",
        "cv": "日向美紅",
        "faction": "新星学園",
        "grade": "教師・その他",
        "star": 3,
        "element": "闇",
        "race": "人間",
        "role": "ATK",
        "weapon": "魔法",
        "hp": 1055,
        "ex": 30,
        "atk": 205,
        "crit": 5.0,
        "exup": 69,
        "ctmin": 14,
        "ctmax": 18,
        "skills": [
        ]
    },
    {
        "id": 1071001,
        "date": "2024/01/11",
        "name": "マッドクーガー キサナ",
        "cv": "月城黒魅",
        "faction": "コラプサー",
        "star": 3,
        "element": "炎",
        "race": "魔族",
        "role": "ATK",
        "weapon": "打撃",
        "hp": 1162,
        "ex": 30,
        "atk": 221,
        "crit": 5.0,
        "exup": 84,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": 1072001,
        "date": "2024/01/11",
        "name": "ちびっこ風紀委員 ミア",
        "cv": "春乃ゆき",
        "faction": "新星学園",
        "grade": "1年生",
        "star": 3,
        "element": "炎",
        "race": "人間",
        "role": "SPD",
        "weapon": "斬撃",
        "hp": 725,
        "ex": 30,
        "atk": 71,
        "crit": 3.0,
        "exup": 15,
        "ctmin": 11,
        "ctmax": 13,
        "skills": [
        ]
    },
    {
        "id": 1073001,
        "date": "2024/01/20",
        "name": "空間の魔女 リノ",
        "cv": "霧宮あおい",
        "faction": "その他",
        "star": 3,
        "element": "水",
        "race": "魔族",
        "role": "SUP",
        "weapon": "魔法",
        "hp": 765,
        "ex": 30,
        "atk": 155,
        "crit": 3.0,
        "exup": 102,
        "ctmin": 13,
        "ctmax": 17,
        "skills": [
        ]
    },
    {
        "id": 1076001,
        "date": "2024/01/31",
        "name": "清澄の雛騎士 モナカ",
        "cv": "加々美澪",
        "faction": "新星学園",
        "grade": "1年生",
        "star": 2,
        "element": "水",
        "race": "人間",
        "role": "SPD",
        "weapon": "斬撃",
        "hp": 459,
        "ex": 25,
        "atk": 61,
        "crit": 3.0,
        "exup": 12,
        "ctmin": 11,
        "ctmax": 13,
        "skills": [
        ]
    },
    {
        "id": 1074001,
        "date": "2024/01/31",
        "name": "お転婆バサラ姫 パルミエ",
        "cv": "乙葉せいら",
        "faction": "新星学園",
        "grade": "3年生",
        "star": 3,
        "element": "水",
        "race": "人間",
        "role": "SPD",
        "weapon": "魔法",
        "hp": 634,
        "ex": 30,
        "atk": 168,
        "crit": 3.0,
        "exup": 18,
        "ctmin": 12,
        "ctmax": 12,
        "skills": [
        ]
    },
    {
        "id": 1075001,
        "date": "2024/02/07",
        "name": "天魔の闇騎士 シフォン",
        "cv": "結城ゆたか",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 3,
        "element": "闇",
        "race": "神族",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 1008,
        "ex": 30,
        "atk": 221,
        "crit": 5.0,
        "exup": 90,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": 1019002,
        "date": "2024/02/13",
        "name": "愛遁チョコギフト せつな",
        "cv": "八ッ橋しなもん",
        "faction": "新星学園",
        "grade": "1年生",
        "star": 3,
        "element": "光",
        "race": "魔族",
        "role": "HEAL",
        "weapon": "魔法",
        "hp": 1607,
        "ex": 30,
        "atk": 63,
        "crit": 3.0,
        "exup": 96,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": 1077001,
        "date": "2024/02/13",
        "name": "光速メイドスター 蘭美",
        "cv": "皆月恋",
        "faction": "新星学園",
        "grade": "3年生",
        "star": 3,
        "element": "光",
        "race": "魔族",
        "role": "SPD",
        "weapon": "打撃",
        "hp": 604,
        "ex": 30,
        "atk": 161,
        "crit": 3.0,
        "exup": 24,
        "ctmin": 10,
        "ctmax": 14,
        "skills": [
        ]
    },
    {
        "id": 1020002,
        "date": "2024/02/20",
        "name": "VR水着配信 ルルカ",
        "cv": "秋元にゃん",
        "faction": "新星学園",
        "grade": "1年生",
        "star": 3,
        "element": "炎",
        "race": "魔族",
        "role": "ATK",
        "weapon": "魔法",
        "hp": 1054,
        "ex": 30,
        "atk": 215,
        "crit": 5.0,
        "exup": 75,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": 1054002,
        "date": "2024/02/28",
        "name": "カードプリンス ユーリス",
        "cv": "猫田かな",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 2,
        "element": "雷",
        "race": "神族",
        "role": "ATK",
        "weapon": "斬撃",
        "hp": 710,
        "ex": 25,
        "atk": 177,
        "crit": 5.0,
        "exup": 57,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": 1009002,
        "date": "2024/02/28",
        "name": "チャームバニー セーラ",
        "cv": "夏野ぱいん",
        "faction": "流星学園",
        "grade": "3年生",
        "star": 3,
        "element": "光",
        "race": "人間",
        "role": "ATK",
        "weapon": "打撃",
        "hp": 1115,
        "ex": 30,
        "atk": 228,
        "crit": 5.0,
        "exup": 66,
        "ctmin": 16,
        "ctmax": 20,
        "skills": [
        ]
    },
    {
        "id": 1013002,
        "date": "2024/03/05",
        "name": "ダイスシューター ユウリ",
        "cv": "椎名みこ",
        "faction": "流星学園",
        "grade": "2年生",
        "star": 3,
        "element": "雷",
        "race": "魔族",
        "role": "SUP",
        "weapon": "打撃",
        "hp": 725,
        "ex": 30,
        "atk": 119,
        "crit": 3.0,
        "exup": 90,
        "ctmin": 12,
        "ctmax": 16,
        "skills": [
        ]
    },
    {
        "id": 1082001,
        "date": "2024/03/12",
        "name": "星選の祓魔師 フェリシー",
        "cv": "逢真井もこ",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 3,
        "element": "雷",
        "race": "人間",
        "role": "ATK",
        "weapon": "打撃",
        "hp": 1209,
        "ex": 30,
        "atk": 252,
        "crit": 5.0,
        "exup": 66,
        "ctmin": 16,
        "ctmax": 20,
        "skills": [
        ]
    },
    {
        "id": 1083001,
        "date": "2024/03/12",
        "name": "暴虐の吸血鬼 ソフレ",
        "cv": "熊田あいす",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 3,
        "element": "雷",
        "race": "魔族",
        "role": "ATK",
        "weapon": "魔法",
        "hp": 1108,
        "ex": 30,
        "atk": 228,
        "crit": 5.0,
        "exup": 78,
        "ctmin": 17,
        "ctmax": 21,
        "skills": [
        ]
    },
    {
        "id": 1060001,
        "date": "2024/03/18",
        "name": "電撃熱唱の歌姫 レミカ",
        "cv": "真壁由依",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 3,
        "element": "雷",
        "race": "人間",
        "role": "HEAL",
        "weapon": "魔法",
        "hp": 1915,
        "ex": 30,
        "atk": 119,
        "crit": 3.0,
        "exup": 120,
        "ctmin": 19,
        "ctmax": 23,
        "skills": [
        ]
    },
    {
        "id": 1078001,
        "date": "2024/03/22",
        "name": "光と再生の魔女 トリュファイナ",
        "cv": "乃葉奈",
        "faction": "その他",
        "star": 3,
        "element": "光",
        "race": "魔族",
        "role": "HEAL",
        "weapon": "魔法",
        "hp": 1705,
        "ex": 30,
        "atk": 158,
        "crit": 5.0,
        "exup": 84,
        "ctmin": 19,
        "ctmax": 22,
        "skills": [
        ]
    },
    {
        "id": 1081001,
        "date": "2024/03/31",
        "name": "静粛なる祈り手 グロリア",
        "cv": "背脂にぼし",
        "faction": "流星学園",
        "grade": "3年生",
        "star": 2,
        "element": "光",
        "race": "神族",
        "role": "SUP",
        "weapon": "斬撃",
        "hp": 518,
        "ex": 25,
        "atk": 91,
        "crit": 3.0,
        "exup": 85,
        "ctmin": 15,
        "ctmax": 19,
        "skills": [
        ]
    },
    {
        "id": 1079001,
        "date": "2024/03/31",
        "name": "試練の守護天使 パテル",
        "cv": "有田菜依",
        "faction": "守護天使",
        "star": 3,
        "element": "闇",
        "race": "神族",
        "role": "SPD",
        "weapon": "斬撃",
        "hp": 302,
        "ex": 30,
        "atk": 197,
        "crit": 3.0,
        "exup": 18,
        "ctmin": 11,
        "ctmax": 13,
        "skills": [
        ]
    },
    {
        "id": 1080001,
        "date": "2024/04/05",
        "name": "燃え盛る炎の旗手 フラン",
        "cv": "春乃いろは",
        "faction": "新星学園",
        "grade": "2年生",
        "star": 3,
        "element": "炎",
        "race": "神族",
        "role": "SUP",
        "weapon": "斬撃",
        "hp": 926,
        "ex": 30,
        "atk": 137,
        "crit": 3.0,
        "exup": 87,
        "ctmin": 12,
        "ctmax": 16,
        "skills": [
        ]
    },
    {
        "id": 1085001,
        "date": "2024/04/10",
        "name": "境界の幼アバター マグダレナ（ちぃ）",
        "cv": "花園ゆぁ",
        "faction": "流星学園",
        "grade": "1年生",
        "star": 3,
        "element": "水",
        "race": "神族",
        "role": "HEAL",
        "weapon": "魔法",
        "hp": 1705,
        "ex": 30,
        "atk": 158,
        "crit": 5.0,
        "exup": 84,
        "ctmin": 19,
        "ctmax": 23,
        "skills": [
        ]
    },
    {
        "id": 1086001,
        "date": "2024/04/10",
        "name": "命脈の幼アバター アルモタヘル（ちぃ）",
